version: "2"
services:
  dcsstv:
    image: rytisgit/dcsstv:uno-platform-dcsstv
    ports:
      - "5000:80"
  websocket-telnet-proxy:
    image: rytisgit/websocket-telnet-proxy:latest
    ports:
      - "5001:80"
  cors-anywhere:
    image: redocly/cors-anywhere:latest
    ports:
      - "3000:8080"
    environment:
      - CORSANYWHERE_WHITELIST=https://localhost,http://localhost,http://localhost:5000
